"""add discovered url

Revision ID: 379fbba3bf18
Revises: b5d62753d1c4
Create Date: 2026-02-02 00:37:47.596005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '379fbba3bf18'
down_revision: Union[str, Sequence[str], None] = 'b5d62753d1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('tech', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'url_hash', name='uq_domain_urlhash')
    )
    op.create_index('ix_discovered_urls_domain_created_id', 'discovered_urls', ["domain_id", "created_at", "id"], unique=False)
    op.create_index(op.f('ix_discovered_urls_host'), 'discovered_urls', ['host'], unique=False)
    op.create_index(op.f('ix_discovered_urls_url_hash'), 'discovered_urls', ['url_hash'], unique=False)
    op.create_table('domain_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_runs_domain_id'), 'domain_runs', ['domain_id'], unique=False)
    op.create_index(op.f('ix_domain_runs_job_id'), 'domain_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_domain_runs_status'), 'domain_runs', ['status'], unique=False)
    op.drop_constraint(op.f('domain_name_key'), 'domain', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('domain_name_key'), 'domain', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_domain_runs_status'), table_name='domain_runs')
    op.drop_index(op.f('ix_domain_runs_job_id'), table_name='domain_runs')
    op.drop_index(op.f('ix_domain_runs_domain_id'), table_name='domain_runs')
    op.drop_table('domain_runs')
    op.drop_index(op.f('ix_discovered_urls_url_hash'), table_name='discovered_urls')
    op.drop_index(op.f('ix_discovered_urls_host'), table_name='discovered_urls')
    op.drop_index('ix_discovered_urls_domain_host', table_name='discovered_urls')
    op.drop_table('discovered_urls')
    # ### end Alembic commands ###
