"""criação tabela subdomain

Revision ID: 6c54e97c14a7
Revises: 84cc711a7879
Create Date: 2025-09-03 22:22:55.391562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c54e97c14a7'
down_revision: Union[str, Sequence[str], None] = '84cc711a7879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subdomain', sa.Column('host', sa.String(), nullable=False))
    op.add_column('subdomain', sa.Column('ip', sa.String(), nullable=False))
    op.add_column('subdomain', sa.Column('doamin_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('subdomain_name_key'), 'subdomain', type_='unique')
    op.create_unique_constraint(None, 'subdomain', ['host'])
    op.drop_constraint(op.f('subdomain_domain_id_fkey'), 'subdomain', type_='foreignkey')
    op.create_foreign_key(None, 'subdomain', 'domain', ['doamin_id'], ['id'])
    op.drop_column('subdomain', 'name')
    op.drop_column('subdomain', 'domain_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subdomain', sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subdomain', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subdomain', type_='foreignkey')
    op.create_foreign_key(op.f('subdomain_domain_id_fkey'), 'subdomain', 'domain', ['domain_id'], ['id'])
    op.drop_constraint(None, 'subdomain', type_='unique')
    op.create_unique_constraint(op.f('subdomain_name_key'), 'subdomain', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('subdomain', 'doamin_id')
    op.drop_column('subdomain', 'ip')
    op.drop_column('subdomain', 'host')
    # ### end Alembic commands ###
