"""arrumando relacao entre subdomain e domain

Revision ID: b5d62753d1c4
Revises: 641f6946ae59
Create Date: 2025-09-04 17:28:59.377560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d62753d1c4'
down_revision: Union[str, Sequence[str], None] = '641f6946ae59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('subdomain_host_key'), 'subdomain', type_='unique')
    op.create_unique_constraint('uq_host_per_domain', 'subdomain', ['host', 'domain_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_host_per_domain', 'subdomain', type_='unique')
    op.create_unique_constraint(op.f('subdomain_host_key'), 'subdomain', ['host'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
