"""atualizando table Domain

Revision ID: ba31bed671dd
Revises: 0653fe250ebe
Create Date: 2025-08-30 10:25:11.474579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba31bed671dd'
down_revision: Union[str, Sequence[str], None] = '0653fe250ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_domain', 'domain', type_='unique')
    op.create_unique_constraint('uq_user_domain', 'domain', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_domain', 'domain', type_='unique')
    # ### end Alembic commands ###
