"""correcao tabela subdomain

Revision ID: edd75a54b782
Revises: 6c54e97c14a7
Create Date: 2025-09-03 22:25:23.459143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd75a54b782'
down_revision: Union[str, Sequence[str], None] = '6c54e97c14a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subdomain', sa.Column('domain_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('subdomain_doamin_id_fkey'), 'subdomain', type_='foreignkey')
    op.create_foreign_key(None, 'subdomain', 'domain', ['domain_id'], ['id'])
    op.drop_column('subdomain', 'doamin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subdomain', sa.Column('doamin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subdomain', type_='foreignkey')
    op.create_foreign_key(op.f('subdomain_doamin_id_fkey'), 'subdomain', 'domain', ['doamin_id'], ['id'])
    op.drop_column('subdomain', 'domain_id')
    # ### end Alembic commands ###
